### ISSUE TITLE
Add peer dependencies for eslint

### ISSUE THREAD

**Issue by riteshe63** [rcorp/standard-project-structure#39]
#35

We need to add peer dependencies "eslint-plugin-jsx-a11y" manually in the "eslint-config-airbnb" module.
Since at the time of installations of the modules, the dependencies and the dev dependencies get installed but not the peer dependencies. So we need to add these manually to the modules.

**Comment by gaurav21r** [comment]
@riteshe63 Please check now!

**Comment by riteshe63** [comment]
ok and thanks.
