### ISSUE TITLE
Folder Structure  of Test Cases.

### ISSUE THREAD

**Issue by riteshe63** [rcorp/standard-project-structure#40]
I am proposing two folder structure for **test** folder:
1. **test**
   The folder structure will contain a folder named as `spec` having defined test folder like: 
   unit,  functional, multibrowser etc.
   
   For ref., Please see the link below 
   https://github.com/webdriverio/webdriverio/tree/master/test
   https://github.com/recharts/recharts/tree/master/test
2. **test**
   The folder structure will have `test` folders as per specification like:
   unit,  functional, multibrowser etc.
   
   For ref., Please see the link below
   https://github.com/dojo/core/tree/master/tests
   https://github.com/google/material-design-lite/tree/mdl-1.x/test

**Comment by gaurav21r** [comment]
@riteshe63 can we have more projects? Based on the list we discussed? Most popular and ones we are familiar with?

Also could you please add _why_ we need a `spec`  inside the main test folder. We discussed this verbally and I asked you to write it as a comment for the benefit of all those using this project?

**Comment by riteshe63** [comment]
Some more projects used by mocha like:
https://github.com/jscs-dev/node-jscs/tree/master/test
https://github.com/eslint/eslint/tree/master/tests
https://github.com/yaniswang/HTMLHint/tree/master/test
https://github.com/bower/bower/tree/master/test
https://github.com/vuejs/vue/tree/dev/test
https://github.com/strongloop/loopback/tree/master/test
https://github.com/serverless/serverless/tree/master/tests
https://github.com/Modernizr/Modernizr/tree/master/test
https://github.com/google/material-design-lite/tree/mdl-1.x/test
https://github.com/expressjs/express/tree/master/test

And we use `spec` folder because  `spec` defines test cases and `config file` will be defined along with `spec`.

**Comment by riteshe63** [comment]
The folder structure will contain a folder named as `spec` having defined test folder like: 
unit, functional, multibrowser etc. And config file of different test cases should be defined within `test` folder.
https://github.com/webdriverio/webdriverio/tree/master/test
https://github.com/recharts/recharts/tree/master/test
https://github.com/jscs-dev/node-jscs/tree/master/test
